[package]
name = "main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# eframe = "0.16.0"
# eframe = { git = "https://github.com/emilk/egui", rev = "366f544" }
eframe = { path = "../../egui/eframe", features = ["persistence"] }
image = "0.24.0"
serde = "1.0.136"
serde_json = "1.0.78"
back = { path = "../back" }
