[package]
name = "main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mc_mod_meta = { path = "../mc_mod_meta" }
eframe = "0.16.0"
# eframe = { git = "https://github.com/emilk/egui", rev = "366f544" }
ferinth = "1.3.0"
