[package]
name = "main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mc_mod_meta = { path = "../mc_mod_meta" }
# eframe = "0.16.0"
# eframe = { git = "https://github.com/emilk/egui", rev = "366f544" }
eframe = { path = "../../../Rust/egui/eframe" }
ferinth = "1.4.1"
tokio = { version = "1.16.1", features = ["rt", "macros", "rt-multi-thread"] }
sha-1 = "0.10.0"
sha2 = "0.10.1"
hex = "0.4.3"
lazy_static = "1.4.0"
regex = "1.5.4"
image = "0.23.14"
