[package]
name = "back"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.16.1", features = ["rt", "rt-multi-thread"] }
# ferinth = "1.4.1"
ferinth = { path = "../../ferinth" }
sha-1 = "0.10.0"
sha2 = "0.10.1"
mc_mod_meta = { path = "../mc_mod_meta" }
regex = "1.5.4"
lazy_static = "1.4.0"
hex = "0.4.3"
bytes = "1.1.0"
# daedalus = "0.1.14"
daedalus = { path = "../../daedalus/daedalus" }
epi = { path = "../../egui/epi" }
thiserror = "1.0.30"

# For their error types
serde_json = "1.0.78"
reqwest = "0.11.9"
