[alias]
lint = "clippy --all-targets -- -W clippy::all -W clippy::nursery -W clippy::pedantic -A clippy::missing_panics_doc -A clippy::missing_errors_doc  -A clippy::module_name_repetitions -A clippy::too_many_lines -A clippy::missing_const_for_fn -A clippy::future_not_send -A clippy::cast_possible_truncation"
# -W rust_2018_idioms
